In [0]:
import pandas as pd

from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
#%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from sklearn.tree import DecisionTreeClassifier

pd.set_option('display.max_rows', None)
studentDataset = pd.read_csv("gdrive/My Drive/Colab Notebooks/student_grade/FinalMarks.csv")
X = studentDataset[['Irregular','Percentage_of_Attendence Marks','Did_Appeared_In_All_The_Class_Test','Percentage_of_Class_Test_Marks','Percentage_of_Mid_Marks','Submitted_Assignments_On_Time','Perfomed_Presentation']]
y=studentDataset[['Final_Exam_Grade']]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.26,random_state=0)


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
print(y_test)
from sklearn.preprocessing import LabelEncoder
### label encode the categorical values and convert them to numbers
le = LabelEncoder()
le.fit(X_train['Irregular'].astype(str))
X_train['Irregular'] = le.transform(X_train['Irregular'].astype(str))
X_test['Irregular'] = le.transform(X_test['Irregular'].astype(str))

     Final_Exam_Grade
132                 3
309                 2
341                 3
196                 0
246                 2
60                  1
155                 3
261                 3
141                 3
214                 3
37                  1
134                 1
113                 1
348                 2
12                  2
59                  1
293                 3
140                 3
206                 3
199                 1
176                 3
268                 3
124                 1
344                 3
175                 3
313                 1
78                  2
15                  1
286                 1
102                 3
170                 3
303                 3
334                 3
225                 1
65                  3
76                  3
90                  3
173                 3
179                 1
399                 1
100                 3
322                 1
6                   2
1                   1
297       

In [0]:
le = LabelEncoder()
le.fit(X_train['Did_Appeared_In_All_The_Class_Test'].astype(str))
X_train['Did_Appeared_In_All_The_Class_Test'] = le.transform(X_train['Did_Appeared_In_All_The_Class_Test'].astype(str))
X_test['Did_Appeared_In_All_The_Class_Test'] = le.transform(X_test['Did_Appeared_In_All_The_Class_Test'].astype(str))

In [0]:
le = LabelEncoder()
le.fit(X_train['Submitted_Assignments_On_Time'].astype(str))
X_train['Submitted_Assignments_On_Time'] = le.transform(X_train['Submitted_Assignments_On_Time'].astype(str))
X_test['Submitted_Assignments_On_Time'] = le.transform(X_test['Submitted_Assignments_On_Time'].astype(str))

In [0]:
le = LabelEncoder()
le.fit(X_train['Perfomed_Presentation'].astype(str))
X_train['Perfomed_Presentation'] = le.transform(X_train['Perfomed_Presentation'].astype(str))
X_test['Perfomed_Presentation'] = le.transform(X_test['Perfomed_Presentation'].astype(str))

In [0]:
##Building the Function for AUC validation
from sklearn.preprocessing import LabelBinarizer
def multiclass_roc_auc_score(y_test,y_pred,average="macro"):
    lb=LabelBinarizer()
    lb.fit(y_test)
    y_test=lb.transform(y_test)
    y_pred=lb.transform(y_pred)
    return  metrics.roc_auc_score(y_test,y_pred,average=average)
##Building the Function for AUC validation ends here

In [0]:
print("#####################")
logRegression=LogisticRegression()
logRegression.fit(X_train,y_train)

y_predictionLogistic=logRegression.predict(X_test)

print("Logistic Regression: ")

print("Accuracy: ",metrics.accuracy_score(y_test, y_predictionLogistic))

aucLog=multiclass_roc_auc_score(y_test,y_predictionLogistic,average="macro")
print("Are under Curve for Logistic Regression: ", aucLog)
print(metrics.confusion_matrix(y_test,y_predictionLogistic))
print("Report for Logistic: ")
print(metrics.classification_report(y_test,y_predictionLogistic))

#####################
Logistic Regression: 
Accuracy:  0.7307692307692307
Are under Curve for Logistic Regression:  0.8031086482267882
[[ 2  1  0  0]
 [ 3 24 10  0]
 [ 0  3 14  7]
 [ 0  0  4 36]]
Report for Logistic: 
              precision    recall  f1-score   support

           0       0.40      0.67      0.50         3
           1       0.86      0.65      0.74        37
           2       0.50      0.58      0.54        24
           3       0.84      0.90      0.87        40

    accuracy                           0.73       104
   macro avg       0.65      0.70      0.66       104
weighted avg       0.75      0.73      0.74       104



In [0]:
print("#####################")
from sklearn.svm import LinearSVC
SVMClassification=LinearSVC(random_state=0)
SVMClassification.fit(X_train,y_train)
y_predictionSVM=SVMClassification.predict(X_test)

print("SVM: ")
print("Accurcy: ",metrics.accuracy_score(y_test, y_predictionSVM))
aucSVM=multiclass_roc_auc_score(y_test,y_predictionSVM,average="macro")
print("Are under Curve for SVM: ", aucSVM)
print(metrics.confusion_matrix(y_test,y_predictionSVM))
print("Report for SVM: ")
print(metrics.classification_report(y_test,y_predictionSVM))



#####################
SVM: 
Accurcy:  0.7596153846153846
Are under Curve for SVM:  0.8083264885017647
[[ 2  1  0  0]
 [ 3 29  5  0]
 [ 0  4 10 10]
 [ 0  1  1 38]]
Report for SVM: 
              precision    recall  f1-score   support

           0       0.40      0.67      0.50         3
           1       0.83      0.78      0.81        37
           2       0.62      0.42      0.50        24
           3       0.79      0.95      0.86        40

    accuracy                           0.76       104
   macro avg       0.66      0.70      0.67       104
weighted avg       0.76      0.76      0.75       104



In [0]:
print("#####################")
DTClassification=DecisionTreeClassifier(random_state=0)
DTClassification.fit(X_train,y_train)
y_predictionDT=DTClassification.predict(X_test)

print("Descision Tree:")
print("Accuracy: ",metrics.accuracy_score(y_test, y_predictionDT))
aucDT=multiclass_roc_auc_score(y_test,y_predictionDT,average="macro")
print("Are under Curve for DT: ", aucDT)
print(metrics.confusion_matrix(y_test,y_predictionDT))

print("Decision Tree: ")
print("Report for Decision Tree: ")
print(metrics.classification_report(y_test,y_predictionDT))

#####################
Descision Tree:
Accuracy:  0.7596153846153846
Are under Curve for DT:  0.8685734078179147
[[ 3  0  0  0]
 [ 4 25  8  0]
 [ 0  2 19  3]
 [ 0  1  7 32]]
Decision Tree: 
Report for Decision Tree: 
              precision    recall  f1-score   support

           0       0.43      1.00      0.60         3
           1       0.89      0.68      0.77        37
           2       0.56      0.79      0.66        24
           3       0.91      0.80      0.85        40

    accuracy                           0.76       104
   macro avg       0.70      0.82      0.72       104
weighted avg       0.81      0.76      0.77       104



In [0]:
print("#####################")
from sklearn.neighbors import KNeighborsClassifier

KNNClassification = KNeighborsClassifier(n_neighbors=4)
KNNClassification.fit(X_train,y_train)
y_predictionKNN=KNNClassification.predict(X_test)

print("KNN: ")
print("Accuracy",metrics.accuracy_score(y_test, y_predictionKNN))
aucKNN=multiclass_roc_auc_score(y_test,y_predictionKNN,average="macro")
print("Are under Curve for KNN: ", aucKNN)
print(metrics.confusion_matrix(y_test,y_predictionKNN))

print("Report for KNN: ")
print(metrics.classification_report(y_test,y_predictionKNN))

#####################
KNN: 
Accuracy 0.7403846153846154
Are under Curve for KNN:  0.8529809085468097
[[ 3  0  0  0]
 [ 3 30  4  0]
 [ 0  5 16  3]
 [ 0  1 11 28]]
Report for KNN: 
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         3
           1       0.83      0.81      0.82        37
           2       0.52      0.67      0.58        24
           3       0.90      0.70      0.79        40

    accuracy                           0.74       104
   macro avg       0.69      0.79      0.71       104
weighted avg       0.78      0.74      0.75       104



In [0]:
print("#####################")
from sklearn.ensemble import AdaBoostClassifier
ADABoostClassification=AdaBoostClassifier()
ADABoostClassification.fit(X_train,y_train)
y_predictionADABoost=ADABoostClassification.predict(X_test)

print("ADA Boost:")
print("Accuracy: ",metrics.accuracy_score(y_test, y_predictionADABoost))
aucADA=multiclass_roc_auc_score(y_test,y_predictionADABoost,average="macro")
print("Are under Curve for ADA: ", aucADA)
print(metrics.confusion_matrix(y_test,y_predictionADABoost))

print("Report for Adaboost: ")
print(metrics.classification_report(y_test,y_predictionADABoost))


#####################
ADA Boost:
Accuracy:  0.7019230769230769
Are under Curve for ADA:  0.8285325212602694
[[ 3  0  0  0]
 [ 3 19 14  1]
 [ 0  1 15  8]
 [ 0  0  4 36]]
Report for Adaboost: 
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         3
           1       0.95      0.51      0.67        37
           2       0.45      0.62      0.53        24
           3       0.80      0.90      0.85        40

    accuracy                           0.70       104
   macro avg       0.68      0.76      0.68       104
weighted avg       0.76      0.70      0.70       104



In [0]:
print("#####################")
from sklearn.neural_network import MLPClassifier
MLPClassification=MLPClassifier(random_state=0)
MLPClassification.fit(X_train,y_train)
y_predictionMLP=MLPClassification.predict(X_test)

print("MLP CLassifier: ")
print("Accuracy",metrics.accuracy_score(y_test, y_predictionMLP))
aucMLP=multiclass_roc_auc_score(y_test,y_predictionMLP,average="macro")
print("Are under Curve for MLP: ", aucMLP)
print(metrics.confusion_matrix(y_test,y_predictionMLP))

print("Report for MLP: ")
print(metrics.classification_report(y_test,y_predictionMLP))

#####################
MLP CLassifier: 
Accuracy 0.75
Are under Curve for MLP:  0.8141546519642888
[[ 2  1  0  0]
 [ 2 24 10  1]
 [ 0  2 15  7]
 [ 0  0  3 37]]
Report for MLP: 
              precision    recall  f1-score   support

           0       0.50      0.67      0.57         3
           1       0.89      0.65      0.75        37
           2       0.54      0.62      0.58        24
           3       0.82      0.93      0.87        40

    accuracy                           0.75       104
   macro avg       0.69      0.72      0.69       104
weighted avg       0.77      0.75      0.75       104



In [0]:
print("#####################")
from sklearn.tree import ExtraTreeClassifier
ExtraTreeClassification=ExtraTreeClassifier(random_state=1)
ExtraTreeClassification.fit(X_train,y_train)
y_predictionET=ExtraTreeClassification.predict(X_test)

print("Extra Tree CLassifier: ")
print("Accuracy",metrics.accuracy_score(y_test, y_predictionET))
aucET=multiclass_roc_auc_score(y_test,y_predictionET,average="macro")
print("Are under Curve for ET: ", aucET)
print(metrics.confusion_matrix(y_test,y_predictionET))

print("Report for ET: ")
print(metrics.classification_report(y_test,y_predictionET))

#####################
Extra Tree CLassifier: 
Accuracy 0.75
Are under Curve for ET:  0.8507961097642641
[[ 3  0  0  0]
 [ 3 29  5  0]
 [ 1  6 13  4]
 [ 0  1  6 33]]
Report for ET: 
              precision    recall  f1-score   support

           0       0.43      1.00      0.60         3
           1       0.81      0.78      0.79        37
           2       0.54      0.54      0.54        24
           3       0.89      0.82      0.86        40

    accuracy                           0.75       104
   macro avg       0.67      0.79      0.70       104
weighted avg       0.77      0.75      0.75       104



In [0]:
print("#####################")
from sklearn.ensemble import VotingClassifier
Voting_Classification = VotingClassifier(estimators=[('svm',SVMClassification) ,('lr', logRegression),('knn', KNNClassification),('descit',DTClassification),('ada',ADABoostClassification),('mlp',MLPClassification),('et',ExtraTreeClassification)],weights=[1,1,1,3,1,1,2],flatten_transform=True)
Voting_Classification.fit(X_train,y_train)
y_predictionVoting=Voting_Classification.predict(X_test)
print("Voting with SVM,Logistic,Knn,Descision Tree, Adaboost, MLP, Extra Tree:")
print("Accuracy: ",metrics.accuracy_score(y_test, y_predictionVoting))

print(metrics.confusion_matrix(y_test,y_predictionVoting))

aucVoting=multiclass_roc_auc_score(y_test,y_predictionVoting,average="macro")
print("Are under Curve for Voting: ", aucVoting)

print("Report for Voting: ")
print(metrics.classification_report(y_test,y_predictionVoting))

print("#####################")

#####################
Voting with SVM,Logistic,Knn,Descision Tree, Adaboost, MLP, Extra Tree:
Accuracy:  0.8173076923076923
[[ 3  0  0  0]
 [ 3 29  5  0]
 [ 0  2 19  3]
 [ 0  0  6 34]]
Are under Curve for Voting:  0.8976902167355956
Report for Voting: 
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         3
           1       0.94      0.78      0.85        37
           2       0.63      0.79      0.70        24
           3       0.92      0.85      0.88        40

    accuracy                           0.82       104
   macro avg       0.75      0.86      0.78       104
weighted avg       0.85      0.82      0.82       104

#####################
